Auto merging bump PR for release workflow (#974)
* script to merge PR

* create draft and publish draft done

* no checks yet

* step references corrected

* zz copy restored

* all checks in place

* bump to 1.23.6

* needs needed change

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -22,10 +22,10 @@ on:
         options:
           - dummy
           - real
-      sec-scanners-config:
+      skip-sec-file-bump:
         type: boolean
-        description: 'Create PR with sec-scanners-config bump'
-        default: true
+        description: 'Do not bump sec-scanners-config file'
+        default: false
       dry-run:
         type: boolean
         description: 'Do not publish'
@@ -69,69 +69,10 @@ jobs:
           NAME: ${{ inputs.name }}
         run: python3 scripts/python/release_label_validator.py
 
-  bump-sec-scanners-config:
-    name: Bump sec-scanners-config
-    needs: validate-release
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Update sec-scanners-config.yaml
-        if: ${{ inputs.sec-scanners-config }}
-        run: scripts/create_scan_config.sh $IMAGE_REPO:${{ inputs.name }} "sec-scanners-config.yaml" ${{ inputs.name }}
-
-      - name: Create PR if anything changed
-        id: pr-needed
-        if: ${{ inputs.sec-scanners-config }}
-        env:
-          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
-        run: |
-          prs=$(gh pr list -A ${{ env.GIT_NAME }} --state open --json headRefName | jq -r '.[] | .headRefName')
-          if echo $prs | tr " " '\n' | grep -F -q -x ${{ env.BRANCH_NAME }}; then
-            echo "PR already exists, no need to create a new one"
-            echo "PR_NUMBER=$(gh pr list --search "base:main head:${{ env.BRANCH_NAME }}" --json number | jq -r '.[] | .number')" >> $GITHUB_ENV
-          elif [ -z "$(git status --porcelain)" ]; then
-            echo "Nothing changed, no need to create PR"
-            echo "PR_NUMBER=-1" >> $GITHUB_ENV
-          else
-            PR_STATUS=$(scripts/create_sec_scanner_bump_pr.sh ${{ inputs.name }})
-            echo "PR_NUMBER=$(echo "$PR_STATUS" | tail -n 1)" >> $GITHUB_ENV          
-          fi
-
-      - name: Await PR merge
-        if: ${{ inputs.sec-scanners-config }}
-        timeout-minutes: 10
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: | 
-          if [ "$PR_NUMBER" -gt 0 ]; then
-            scripts/await_pr_merge.sh
-            git push origin -d ${{ env.BRANCH_NAME }}
-          else
-            echo "Step skipped"
-          fi
-
-      - name: Save latest commit ref
-        id: pull-ref
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git checkout main
-          git pull
-          LATEST_COMMIT=$(git rev-parse HEAD)
-          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
-          echo "Latest commit ref $LATEST_COMMIT"
-
-    outputs:
-      latest_commit: ${{ steps.pull-ref.outputs.latest_commit }}  
 
   build-image:
     name: Build image
-    needs: [create-draft, bump-sec-scanners-config]
+    needs: [validate-release]
     uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
     with:
       name: btp-manager
@@ -141,7 +82,6 @@ jobs:
 
   run-unit-tests:
     name: Unit tests
-    needs: create-draft
     uses: "./.github/workflows/run-unit-tests-reusable.yaml"
 
   run-e2e-tests:
@@ -224,6 +164,107 @@ jobs:
       image-registry: europe-docker.pkg.dev/kyma-project/prod/btp-manager
       image-tag: ${{ github.event.inputs.name }}
 
+  bump-sec-scanners-config:
+    name: Bump sec-scanners-config
+    needs: [validate-release, run-unit-tests, run-e2e-tests, run-stress-tests, run-e2e-upgrade-tests, run-e2e-upgrade-while-deleting-tests]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - run: git pull
+
+      - name: Update sec-scanners-config.yaml
+        if: ${{ !inputs.skip-sec-file-bump }}
+        run: scripts/create_scan_config.sh $IMAGE_REPO:${{ inputs.name }} "sec-scanners-config.yaml" ${{ inputs.name }}
+
+      - name: Check if any PR was merged during release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          COMMIT_SHA=$(gh api repos/${{ env.KYMA_BTP_MANAGER_REPO }}/commits -q '.[0].sha')
+          echo "Latest commit sha: $COMMIT_SHA"
+          echo "Workflow sha: ${{ github.sha }}"
+          if [ "$COMMIT_SHA" != "${{ github.sha }}" ]; then
+            echo "::error ::a PR was merged during the release. Don't rerun this workflow, create a new release with the same version"
+            exit 1
+          fi
+
+      - name: Create PR if anything changed
+        id: pr-needed
+        if: ${{ !inputs.skip-sec-file-bump }}
+        env:
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          prs=$(gh pr list -A ${{ env.GIT_NAME }} --state open --json headRefName | jq -r '.[] | .headRefName')
+          if echo $prs | tr " " '\n' | grep -F -q -x ${{ env.BRANCH_NAME }}; then
+            echo "PR already exists, no need to create a new one"
+            echo "PR_NUMBER=$(gh pr list --search "base:main head:${{ env.BRANCH_NAME }}" --json number | jq -r '.[] | .number')" >> $GITHUB_ENV
+          elif [ -z "$(git status --porcelain)" ]; then
+            echo "Nothing changed, no need to create PR"
+            echo "PR_NUMBER=-1" >> $GITHUB_ENV
+          else
+            PR_STATUS=$(scripts/create_sec_scanner_bump_pr.sh ${{ inputs.name }})
+            echo "PR_NUMBER=$(echo "$PR_STATUS" | tail -n 1)" >> $GITHUB_ENV          
+          fi
+
+      - name: Merge PR
+        if: ${{ !inputs.skip-sec-file-and-chart-bump }}
+        env:
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+          REPOSITORY: ${{ env.KYMA_BTP_MANAGER_REPO }}
+        run: |
+          if [ "$PR_NUMBER" -gt 0 ]; then
+            scripts/merge_pr.sh
+          else
+            echo "Step skipped"
+          fi
+
+      - name: Await PR merge
+        if: ${{ !inputs.skip-sec-file-bump }}
+        timeout-minutes: 10
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [ "$PR_NUMBER" -gt 0 ]; then
+            scripts/await_pr_merge.sh
+            git push origin -d ${{ env.BRANCH_NAME }}
+          else
+            echo "Step skipped"
+          fi
+
+      - name: Check if any PR have been merged before merging the bump PR
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [ "$PR_NUMBER" -gt 0 ]; then
+            COMMIT_SHA=$(gh api repos/${{ env.KYMA_BTP_MANAGER_REPO }}/commits -q '.[1].sha')
+            echo "Latest commit sha: $COMMIT_SHA"
+            echo "Bump sha: ${{ github.sha }}"
+            if [ "$COMMIT_SHA" != "${{ github.sha }}" ]; then
+              echo "::error ::a PR have been merged before merging the bump PR. Don't rerun this workflow. Create a new release with the same version"
+              exit 1 
+          fi
+          else
+            echo "Step skipped"
+          fi   
+
+      - name: Save latest commit ref
+        id: pull-ref
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git checkout main
+          git pull
+          LATEST_COMMIT=$(git rev-parse HEAD)
+          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
+          echo "Latest commit ref $LATEST_COMMIT"
+
+    outputs:
+      latest_commit: ${{ steps.pull-ref.outputs.latest_commit }}
+
   create-draft:
     name: Create draft release
     needs: bump-sec-scanners-config
@@ -235,6 +276,18 @@ jobs:
         with:
           fetch-depth: 0
           ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
+
+      - name: Check if any PR was merged after security scanner config bump
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          COMMIT_SHA=$(gh api repos/${{ env.KYMA_BTP_MANAGER_REPO }}/commits -q '.[0].sha')
+          echo "Latest commit sha: $COMMIT_SHA"
+          echo "Bump sha: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}"
+          if [ "$COMMIT_SHA" != "${{ needs.bump-sec-scanners-config.outputs.latest_commit}}" ]; then
+            echo "::error ::a PR was merged after the security scanner config bump. Don't rerun this workflow, create a new release with the same version"
+            exit 1 
+          fi
 
       - name: Set up go environment
         uses: actions/setup-go@v4
@@ -262,12 +315,24 @@ jobs:
           git tag ${{ github.event.inputs.name }}
           git push origin ${{ github.event.inputs.name }}
 
+      - name: Check if any PR may have been merged before creating the tag and draft release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          COMMIT_SHA=$(gh api repos/${{ env.KYMA_BTP_MANAGER_REPO }}/commits -q '.[0].sha')
+          echo "Latest commit sha: $COMMIT_SHA"
+          echo "Bump sha: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}"
+          if [ "$COMMIT_SHA" != "${{ needs.bump-sec-scanners-config.outputs.latest_commit}}" ]; then
+            echo "::error ::a PR may have been merged before the tag and draft release were created. Delete the tag and the draft release. Don't rerun this workflow. Create a new release with the same version"
+            exit 1 
+          fi
+
     outputs:
       release_id: ${{ steps.create-draft.outputs.release_id }}
 
   publish-release:
     name: Publish release
-    needs: [create-draft, run-unit-tests, run-e2e-tests, run-e2e-upgrade-tests, run-stress-tests, run-e2e-upgrade-while-deleting-tests]
+    needs: [create-draft]
     if: ${{ !inputs.dry-run }}
     runs-on: ubuntu-latest
 
