Do not use kyma cli (#567)
* tracing to figure out how it works now

double manifest

target corrected

go environment step added

running make instead of downloading OCI

apply manifest

setting image name for deployment

dump btp-operator json

using undeploy

manifest file creation

remove dumping btp-operator json

pwd added

changing release process - partially

kustomization yaml removed

reverting run_module_image

reverting kustomization.yaml

kubebuilder-project added back

simplifying

upgrade tests addressed by without fetching manifest

upgrade tests addressed with one todo left

last todo for upgrade tests

await script renamed

stress tests updated

manifest file does not change its name

typo corrected

release.sh simplified

manifest for relase created by kustomize

references to local envs corrected

references to local envs corrected again

simplified env passing

duplication with image repo for now

tracing create sec scan file

typo corrected

setting go environment for stress tests

less arguments

reverting module-build target

base manifest referred

redirection not needed

setting go environment for upgrade tests

setting go environment for upgrade tests in place (the proper one)

stash show for debugging purposes

create manifest in release workflow

debugging Makefile

upload assets script added

creating manifest and uploading assets in the workflow

more info from create-manifest step

token name changed

steps merged

steps split again

testing bump

reverting if in validation

reverting to original bumping

removing todos

* upload assets script added

* script name shortened

* less switches in curl call

* tracing and out-of-date comment removed

* review remarks

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -2,7 +2,6 @@ name: "Create release"
 run-name: Create release ${{ inputs.name }}
 
 env:
-  MODULE_REPO: europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator
   IMAGE_REPO: europe-docker.pkg.dev/kyma-project/prod/btp-manager
   KYMA_BTP_MANAGER_REPO: ${{ github.repository_owner }}/btp-manager
   GIT_EMAIL: team-gopher+1@sap.com
@@ -49,16 +48,13 @@ jobs:
       - name: Check if tag already exists
         run: |
           if [ $(git tag -l ${{ inputs.name }}) ]; then
-            echo "::error ::Tag ${{ inputs.name }} already exists"
-            exit 1
+            echo "::error ::Tag ${{ inputs.name }} already exists" && exit 1
           fi
 
       - name: Check for existing artifacts from previous release runs
         env:
-          BTP_OPERATOR_REPO: ${{ env.MODULE_REPO }}
-          BTP_MANAGER_REPO: ${{ env.IMAGE_REPO }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: "./scripts/check_artifacts_existence.sh ${{ inputs.name }} ${{ inputs.name }}"
+        run: "./scripts/check_artifacts_existence.sh ${{ inputs.name }}"
 
       - name: Setup python
         uses: actions/setup-python@v4
@@ -88,9 +84,10 @@ jobs:
 
       - name: Update sec-scanners-config.yaml
         if: ${{ inputs.sec-scanners-config }}
-        run: scripts/create_scan_config.sh ${{env.IMAGE_REPO}}:${{ inputs.name }} "sec-scanners-config.yaml" ${{ inputs.name }}
+        run: scripts/create_scan_config.sh $IMAGE_REPO:${{ inputs.name }} "sec-scanners-config.yaml" ${{ inputs.name }}
 
       - name: Create PR if anything changed
+        id: pr-needed
         if: ${{ inputs.sec-scanners-config }}
         env:
           GH_TOKEN: ${{ secrets.BOT_TOKEN }}
@@ -106,7 +103,7 @@ jobs:
             PR_STATUS=$(scripts/create_sec_scanner_bump_pr.sh ${{ inputs.name }})
             echo "PR_NUMBER=$(echo "$PR_STATUS" | tail -n 1)" >> $GITHUB_ENV          
           fi
-          
+
       - name: Await PR merge
         if: ${{ inputs.sec-scanners-config }}
         timeout-minutes: 10
@@ -139,21 +136,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Wait for post-btp-manager-module-build status
-        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
-        id: wait-for-module-build-status
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          statusName: "post-btp-manager-module-build"
-          timeoutSeconds: "300"
-          ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
-
-      - name: Check if post-btp-manager-module-build status is success
-        if: steps.wait-for-module-build-status.outputs.state != 'success'
-        run: |
-            echo 'post-btp-manager-module-build failed.'
-            exit 1
-
       - name: Wait for post-btp-manager-build status
         uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
         id: wait-for-image-build-status
@@ -169,6 +151,7 @@ jobs:
           echo 'post-btp-manager-build failed.'
           exit 1
   
+
   run-unit-tests:
     name: Unit tests
     needs: create-draft
@@ -181,9 +164,7 @@ jobs:
     secrets: inherit
     with:
       image-tag: ${{ github.event.inputs.name }}
-      module-tag: ${{ github.event.inputs.name }}
       image-repo: europe-docker.pkg.dev/kyma-project/prod/btp-manager
-      module-repo: europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator
       credentials-mode: ${{ github.event.inputs.credentials }}
       last-k3s-versions: ${{ github.event.inputs.k3s-versions || vars.LAST_K3S_VERSIONS }}
 
@@ -196,34 +177,37 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Set up go environment
+        uses: actions/setup-go@v4
+        with:
+          go-version-file: 'go.mod'
+
       - name: Prepare k3s cluster and docker registry
         run: "./scripts/testing/k3s-setup.sh --wait"
 
       - name: Wait for artifacts
         env:
-          BTP_OPERATOR_REPO: ${{ env.MODULE_REPO }}
-          BTP_MANAGER_REPO: ${{ env.IMAGE_REPO }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: "./scripts/await_artifacts.sh ${{ inputs.name }} ${{ inputs.name }}"
+        run: "./scripts/await_image.sh ${{ inputs.name }}"
 
       - name: Install BTP Manager and SAP BTP Operator
         timeout-minutes: 2
-        run: "./scripts/testing/install.sh $MODULE_REPO:${{ inputs.name }} dummy ci"
+        run: "./scripts/testing/install_module.sh $IMAGE_REPO:${{ inputs.name }} dummy ci"
 
       - name: BTP Manager and SAP BTP Operator controller resources usage
-        run: ./scripts/testing/check_top.sh
+        run: "./scripts/testing/check_top.sh"
         
       - name: Run stress test - instances and bindings
-        run: ./scripts/testing/stress-mem-instances-bindings.sh 500 30
+        run: "./scripts/testing/stress-mem-instances-bindings.sh 500 30"
 
       - name: BTP Manager and SAP BTP Operator controller resources usage
-        run: ./scripts/testing/check_top.sh
+        run: "./scripts/testing/check_top.sh"
 
       - name: Run stress test - secrets and configmaps
         run: "./scripts/testing/stress-mem-secrets-configmaps.sh 120"
 
       - name: BTP Manager and SAP BTP Operator controller resources usage
-        run: ./scripts/testing/check_top.sh
+        run: "./scripts/testing/check_top.sh"
 
   run-e2e-upgrade-tests:
     name: E2E upgrade tests
@@ -233,9 +217,7 @@ jobs:
     uses: "./.github/workflows/run-e2e-upgrade-tests-reusable.yaml"
     with:
       image-tag: ${{ github.event.inputs.name }}
-      module-tag: ${{ github.event.inputs.name }}
       image-repo: europe-docker.pkg.dev/kyma-project/prod/btp-manager
-      module-repo: europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator
 
   create-draft:
     name: Create draft release
@@ -249,6 +231,11 @@ jobs:
           fetch-depth: 0
           ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
 
+      - name: Set up go environment
+        uses: actions/setup-go@v4
+        with:
+          go-version-file: 'go.mod'
+
       - name: Create draft release
         id: create-draft
         env:
@@ -256,6 +243,14 @@ jobs:
         run: |
           RELEASE_ID=$(./scripts/create_draft_release.sh ${{ github.event.inputs.name }})
           echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
+
+      - name: Create manifest and upload assets
+        id: create-manifest
+        env:
+          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          make create-manifest
+          ./scripts/upload_assets.sh ${{ steps.create-draft.outputs.release_id }}
 
       - name: Create lightweight tag
         run: |
