Migrate to github apps

diff --git a/.github/workflows/module-version-submit.yaml b/.github/workflows/module-version-submit.yaml
--- a/.github/workflows/module-version-submit.yaml
+++ b/.github/workflows/module-version-submit.yaml
@@ -13,7 +13,6 @@ env:
   FULL_MODULE_NAME: kyma-project.io/module/btp-operator
 
   # GitHub repositories
-  MODULE_MANIFESTS_WITH_USER: "https://${{ vars.GIT_USER_NAME }}:${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MODULE_MANIFESTS_REPO_NAME }}.git"
   BTP_MANAGER_RELEASES_URL: "https://github.com/kyma-project/btp-manager/releases"
   BTP_MANAGER_REPO: "kyma-project/btp-manager"
 
@@ -21,9 +20,6 @@ env:
   DEFAULT_CR_FILENAME: btp-operator.yaml
   MANIFEST_FILENAME: btp-manager.yaml
   SCAN_CONFIG_FILENAME: sec-scanners-config.yaml
-
-  # needed by gh cli for GitHub enterprise
-  GH_ENTERPRISE_TOKEN: ${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}
 
   # needed by gh cli for local repo
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -50,13 +46,23 @@ jobs:
       - name: Validate required environment variables
         shell: bash
         run: |
-          [ -z "${{ vars.DOC_URL }}" ] && echo "DOC_URL is required" && exit 1 
-          [ -z "${{ vars.GIT_USER_EMAIL }}" ] && echo "GIT_USER_EMAIL is required" && exit 1 
-          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1 
-          [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1 
-          [ -z "${{ vars.IMAGE_REPO }}" ] && echo "IMAGE_REPO is required" && exit 1 
-          [ -z "${{ vars.MODULE_MANIFESTS_REPO_NAME }}" ] && echo "MODULE_MANIFESTS_REPO_NAME is required" && exit 1 
+          [ -z "${{ vars.DOC_URL }}" ] && echo "DOC_URL is required" && exit 1
+          [ -z "${{ vars.GIT_USER_EMAIL }}" ] && echo "GIT_USER_EMAIL is required" && exit 1
+          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1
+          [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1
+          [ -z "${{ vars.IMAGE_REPO }}" ] && echo "IMAGE_REPO is required" && exit 1
+          [ -z "${{ vars.MODULE_MANIFESTS_REPO_NAME }}" ] && echo "MODULE_MANIFESTS_REPO_NAME is required" && exit 1
           echo "Validated"
+
+      - name: Generate enterprise bot token
+        id: enterprise-bot-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ vars.GOPHER_TOOLS_BOT_APP_ID }}
+          private-key: ${{ secrets.GOPHER_TOOLS_BOT_APP_PRIVATE_KEY }}
+          github-api-url: https://${{ vars.GH_TOOLS_HOST }}/api/v3
+          owner: kyma
+          repositories: module-manifests
 
       - name: Use default (latest) Release Tag
         if: inputs.releaseTag == 'use latest release'
@@ -85,7 +91,7 @@ jobs:
 
       - name: Setup git and clone repo
         env:
-          GH_TOKEN: ${{ secrets.BOT_TOKEN_GITHUB_TOOLS }}
+          MODULE_MANIFESTS_WITH_USER: "https://x-access-token:${{ steps.enterprise-bot-token.outputs.token }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MODULE_MANIFESTS_REPO_NAME }}.git"
         run: |
           git config --global user.email ${{ vars.GIT_USER_EMAIL }}
           git config --global user.name ${{ vars.GIT_USER_NAME }}
@@ -133,6 +139,8 @@ jobs:
 
       - name: Commit and push changes
         working-directory: module-manifests
+        env:
+          MODULE_MANIFESTS_WITH_USER: "https://x-access-token:${{ steps.enterprise-bot-token.outputs.token }}@${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MODULE_MANIFESTS_REPO_NAME }}.git"
         run: |
           git add .
           git commit -m "Configuration files update"
@@ -144,8 +152,10 @@ jobs:
         shell: bash
         env:
           MODULE_MANIFESTS_REPO_URL: "https://${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MODULE_MANIFESTS_REPO_NAME }}"
+          GH_ENTERPRISE_TOKEN: ${{ steps.enterprise-bot-token.outputs.token }}
+          GH_HOST: ${{ vars.GH_TOOLS_HOST }}
         run: |
-          prs=$(gh pr list -R "${MODULE_MANIFESTS_REPO_URL}" -A ${{ vars.GIT_USER_NAME }} --state open --json headRefName | jq -r '.[] | .headRefName')
+          prs=$(gh pr list -R "${MODULE_MANIFESTS_REPO_URL}" -A app/kyma-gopher --state open --json headRefName | jq -r '.[] | .headRefName')
 
           if echo $prs | tr " " '\n' | grep -F -q -x ${BRANCH_NAME}; then
               echo "Opened PR already exists, no need to create new one, PR will be updated by push from previous step"
@@ -157,6 +167,5 @@ jobs:
             -H ${BRANCH_NAME} \
             -R https://${{ vars.GH_TOOLS_HOST }}/kyma/${{ vars.MODULE_MANIFESTS_REPO_NAME }}/ \
             --title "Submit BTP Manager version ${TAG}" \
-            --fill \
             --body "${BTP_MANAGER_RELEASES_URL}/${TAG}" \
             | tee $GITHUB_STEP_SUMMARY
