Testsbenchmarks (#113)
* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

diff --git a/.github/workflows/run-unit-tests-debug.yaml b/.github/workflows/run-unit-tests-debug.yaml
--- a/.github/workflows/run-unit-tests-debug.yaml
+++ b/.github/workflows/run-unit-tests-debug.yaml
@@ -21,9 +21,11 @@ jobs:
         FAIL=0
         while true; do
           make -i -k test
-          if [ $? == 0 ]; then
-              echo "(COUNT OF) OK -> $OK"
+          if [ $? -eq 0 ]; then
+            ((OK++))
+            echo "(COUNT OF) OK -> $OK"
           else
-              echo "(COUNT OF) FAIL -> $FAIL
+            ((FAIL++))
+            echo "(COUNT OF) FAIL -> $FAIL"
           fi
         done
