env validation added

diff --git a/.github/workflows/run-e2e-tests-reusable.yaml b/.github/workflows/run-e2e-tests-reusable.yaml
--- a/.github/workflows/run-e2e-tests-reusable.yaml
+++ b/.github/workflows/run-e2e-tests-reusable.yaml
@@ -40,6 +40,7 @@ jobs:
       - name: Validate required environment variables
         shell: bash
         run: |
+          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1 
           [ -z "${{ vars.LAST_K3S_VERSIONS }}" ] && echo "LAST_K3S_VERSIONS is required" && exit 1 
           echo "Validated"
       - name: Checkout code
