Testsbenchmarks (#117)
* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

* wip - temp commit msg

diff --git a/.github/workflows/run-unit-tests-debug.yaml b/.github/workflows/run-unit-tests-debug.yaml
--- a/.github/workflows/run-unit-tests-debug.yaml
+++ b/.github/workflows/run-unit-tests-debug.yaml
@@ -1,4 +1,4 @@
-name: Run unit tests (reusable)
+name: Run unit tests (debug)
 
 on:
   workflow_dispatch:
@@ -18,6 +18,15 @@ jobs:
     - name: Run make test
       shell: bash
       run: |
+        OK=0
+        FAIL=0
         while true; do
-          make -i test
+          make test > /dev/null
+          if [ $? -eq 0 ]; then
+            ((OK++))
+            echo "(COUNT OF) OK -> $OK"
+          else
+            ((FAIL++))
+            echo "(COUNT OF) FAIL -> $FAIL"
+          fi
         done
